---
aliases:
  gh-status-hooks-tests: &gh-status-hooks-tests
    on_success:
      put: gh-status
      inputs: [ java-buildpack-memory-calculator ]
      params: { state: success, context: test-and-build-and-deploy-only-on-main/tests }
    on_failure:
      put: gh-status
      inputs: [ java-buildpack-memory-calculator ]
      params: { state: failure, context: test-and-build-and-deploy-only-on-main/tests }
    on_error:
      put: gh-status
      inputs: [ java-buildpack-memory-calculator ]
      params: { state: error, context: test-and-build-and-deploy-only-on-main/tests }
    on_abort:
      put: gh-status
      inputs: [ java-buildpack-memory-calculator ]
      params: { state: error, context: test-and-build-and-deploy-only-on-main/tests }
  gh-status-hooks-build: &gh-status-hooks-build
    on_success:
      put: gh-status
      inputs: [ java-buildpack-memory-calculator ]
      params: { state: success, context: test-and-build-and-deploy-only-on-main/build }
    on_failure:
      put: gh-status
      inputs: [ java-buildpack-memory-calculator ]
      params: { state: failure, context: test-and-build-and-deploy-only-on-main/build }
    on_error:
      put: gh-status
      inputs: [ java-buildpack-memory-calculator ]
      params: { state: error, context: test-and-build-and-deploy-only-on-main/build }
    on_abort:
      put: gh-status
      inputs: [ java-buildpack-memory-calculator ]
      params: { state: error, context: test-and-build-and-deploy-only-on-main/build }
  gh-status-set-pending-tests: &gh-status-set-pending-tests
    put: gh-status
    inputs: [ java-buildpack-memory-calculator ]
    params: { state: pending, context: test-and-build-and-deploy-only-on-main/tests }
  gh-status-set-pending-build: &gh-status-set-pending-build
    put: gh-status
    inputs: [ java-buildpack-memory-calculator ]
    params: { state: pending, context: test-and-build-and-deploy-only-on-main/build }

var:
  memory-calculator-repository: &memory-calculator-repository-config
    uri: https://github.com/instana/java-buildpack-memory-calculator.git
    username: ((project-berlin-gh-token))
    password: x-oauth-basic
    branch: ((branch))
    git_config:
      - name: user.name
        value: Stan
      - name: user.email
        value: stan@instana.com

resource_types:

  - name: cogito
    type: registry-image
    check_every: never
    source:
      repository: delivery.instana.io/int-docker-cogito-instana-local/cogito
      tag: latest
      username: ((delivery-instana-io-internal-project-artifact-read-writer-creds.username))
      password: ((delivery-instana-io-internal-project-artifact-read-writer-creds.password))

resources:
  - name: java-buildpack-memory-calculator
    type: git
    icon: github
    source:
      <<: *memory-calculator-repository-config

  - name: gh-status
    type: cogito
    source:
      owner: instana
      repo: java-buildpack-memory-calculator
      access_token: ((instanacd-github-api-token))
      context_prefix: concourse
      github_host: github.com

jobs:
  - name: self-update
    max_in_flight: 1
    plan:
      - get: java-buildpack-memory-calculator
        trigger: true
      - task: render-pipeline-template
        # see notes in the task file about why we need to copy-paste this task.
        file: java-buildpack-memory-calculator/ci/render-template-task.yml
        input_mapping:
          repo: java-buildpack-memory-calculator
        vars:
          template: ci/pipeline.yml  # this path has to be relative to 'repo'
          branch: ((branch))
      - set_pipeline: self
        file: rendered/pipeline.yml
        vars:
          branch: ((branch))
          project-berlin-gh-token: ((project-berlin-gh-token))
          delivery-instana-io-release-project-artifact-read-writer-creds: ((delivery-instana-io-release-project-artifact-read-writer-creds))

  - name: test-and-build-and-deploy-only-on-main
    max_in_flight: 1
    plan:
      - get: java-buildpack-memory-calculator
        trigger: true
        passed: [ self-update ]
      - <<: *gh-status-set-pending-tests
      - <<: *gh-status-set-pending-build
      - task: tests
        <<: *gh-status-hooks-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: registry.access.redhat.com/ubi8/go-toolset
              tag: 1.20.10
          inputs:
            - name: java-buildpack-memory-calculator
          run:
            path: java-buildpack-memory-calculator/ci/unit-test.sh

      - task: build
        <<: *gh-status-hooks-build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: registry.access.redhat.com/ubi8/ubi-minimal
          inputs:
            - name: java-buildpack-memory-calculator
          outputs:
            - name: builds
          params:
            SOURCE_DIR: java-buildpack-memory-calculator
            TARGET_DIR: builds
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                microdnf -y install tar gzip wget make findutils
                
                # install newest go version
                export GO_VERSION="1.20.13"
                export GO_SHAR256="9a9d3dcae2b6a638b1f2e9bd4db08ffb39c10e55d9696914002742d90f0047b5 go${GO_VERSION}.linux-amd64.tar.gz"
                export GO_BINARY="go${GO_VERSION}.linux-amd64.tar.gz"
                wget "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz"
                echo "${GO_SHAR256}" | sha256sum --check
                gunzip "${GO_BINARY}"
                tar xf "${GO_BINARY//.gz/}"
                mv go /usr/local/bin
                export PATH=$PATH:/usr/local/bin/go/bin/
                export SOURCE_DIR="$(pwd)/${SOURCE_DIR}"
                export TARGET_DIR="$(pwd)/${TARGET_DIR}"
                bash -x ${SOURCE_DIR}/ci/package.sh

      - load_var: version
        file: java-buildpack-memory-calculator/VERSION
        reveal: true
      - task: deploy_to_artifactory
        yx_if:
          - eq: [((branch)), main]
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: maven
          inputs:
            - name: java-buildpack-memory-calculator
            - name: builds
          params:
            VERSION: ((.:version))
            DELIVERY_ARTIFACTORY_GENERIC_BASE_URL: ((delivery-artifactory-generic-agent-release-url))
            DELIVERY_ARTIFACTORY_USERNAME: ((delivery-instana-io-release-project-artifact-read-writer-creds.username))
            DELIVERY_ARTIFACTORY_PASSWORD: ((delivery-instana-io-release-project-artifact-read-writer-creds.password))
          run:
            path: bash
            args:
              - -c
              - |
                set -e
                
                regex='memory-calculator_(.+)'
                for filename in builds/memory-calculator_*; do
                  [[ $(basename "${filename}") =~ ${regex} ]] && \
                    bash -x java-buildpack-memory-calculator/ci/deploy_to_artifactory.sh "${filename}" "${BASH_REMATCH[1]}" "${VERSION}"
                done
